apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-reader
  labels:
    app: log-reader
spec:
  selector:
    matchLabels:
      app: log-reader
  template:
    metadata:
      labels:
        app: log-reader
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: HTTPS_PORT
              value: "8443"
          command:
            - sh
            - -c
            - sleep infinity
          volumeMounts:
            - name: node-logs
              mountPath: /node-logs
              readOnly: true
      volumes:
        - name: node-logs
          hostPath:
            path: /var/log
            type: Directory
