apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ru">
    <head>
      <meta charset="UTF-8">
      <title>ДЗ 2.3 — Задание 1</title>
    </head>
    <body>
      <h1>Kubernetes ConfigMap</h1>
      <p>Страница подключена к Nginx через ConfigMap.</p>
      <p>Pod содержит контейнеры nginx и multitool.</p>
    </body>
    </html>
