apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ .Values.backend.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.backend.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
